// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzukLAtl4QGJ9MTU5G4ri7wY4fg-2roM',
    appId: '1:443170641219:android:26add17b2054596b1c0bf6',
    messagingSenderId: '443170641219',
    projectId: 'library-app-daf1d',
    storageBucket: 'library-app-daf1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFzukLAtl4QGJ9MTU5G4ri7wY4fg-2roM',
    appId: '1:443170641219:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '443170641219',
    projectId: 'library-app-daf1d',
    storageBucket: 'library-app-daf1d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzukLAtl4QGJ9MTU5G4ri7wY4fg-2roM',
    appId: '1:443170641219:web:YOUR_WEB_APP_ID',
    messagingSenderId: '443170641219',
    projectId: 'library-app-daf1d',
    storageBucket: 'library-app-daf1d.firebasestorage.app',
  );
}
